### ISSUE TITLE
Get resourcePath from transaction

### ISSUE THREAD

**Issue by ThanhQuang1410** [Kottidev/react-native-oppwa#4]
Hi, I have some trouble in getting resourcePath from transaction in Android. It seem to be result from promise transactionPayment just like this {"OS": "android"}. Can you give me some clue?

**Comment by Kottidev** [comment]
@ThanhQuang1410  

You need to use DeviceEventEmitter with Android
`DeviceEventEmitter.addListener("transactionStatus", (transaction)=> { console.log(transaction) })`

**Comment by ThanhQuang1410** [comment]
OMG!!
You are my savior. Thanks for your awesome repo. It helps my project a lot!!
